---
abstract: 'Help integrate Class::DBI with JSON::XS'
author:
  - 'Graham TerMarsch <cpan@howlingfrog.com>'
build_requires:
  DBD::SQLite: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  JSON::XS: '0'
  Test::DiagINC: '0.002'
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-DBI-Plugin-TO_JSON
no_index:
  directory:
    - t
    - xt
requires:
  Class::DBI: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/bleargh45/Class-DBI-Plugin-TO_JSON/issues
  repository: git://github.com/bleargh45/Class-DBI-Plugin-TO_JSON.git
version: '0.04'
x_generated_by_perl: v5.32.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_static_install: 1
